apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  # maxScaleRef:
  #   name: maxscale

  # bootstrapFrom:
  #   backupContentType: Physical
  #   s3:
  #     bucket: database
  #     prefix: mariadb-repl/physical
  #     endpoint: minio.storage.svc.cluster.local:443
  #     accessKeyIdSecretKeyRef:
  #       name: minio
  #       key: access-key-id
  #     secretAccessKeySecretKeyRef:
  #       name: minio
  #       key: secret-access-key
  #     tls:
  #       enabled: true
  #       caSecretKeyRef:
  #         name: homelab-bundle
  #         key: ca.crt
  #   stagingStorage:
  #     persistentVolumeClaim:
  #       resources:
  #         requests:
  #           storage: 10Gi
  #       accessModes:
  #         - ReadWriteOnce
  #   restoreJob:
  #     resources:
  #       requests:
  #         cpu: 1
  #         memory: 512Mi
  #       limits:
  #         cpu: 1
  #         memory: 512Mi

  storage:
    size: 30Gi
    storageClassName: topolvm

  replicas: 3

  replication:
    enabled: true
    primary:
      autoFailover: true
      autoFailoverDelay: 0s
    replica:
      replPasswordSecretKeyRef:
        name: mariadb
        key: password
      bootstrapFrom:
        physicalBackupTemplateRef:
          name: physicalbackup-tpl
      recovery:
        enabled: true
        errorDurationThreshold: 30s
    gtidStrictMode: true
    # semiSyncEnabled: false
    # semiSyncAckTimeout: 10s
    # semiSyncWaitPoint: AfterSync
    # syncBinlog: 1

  metrics:
    enabled: true

  resources:
    requests:
      cpu: 4
      memory: 4Gi
    limits:
      cpu: 4
      memory: 4Gi

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    max_allowed_packet=1G
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=3200MB
    innodb_flush_method=O_DIRECT
    thread_handling=pool-of-threads
    thread_pool_size=4
    slave_parallel_threads=4

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  affinity:
    antiAffinityEnabled: true
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.mmontes.io/type
                operator: In
                values:
                  - compute-large

  livenessProbe:
    failureThreshold: 10
    periodSeconds: 10
    timeoutSeconds: 5

  readinessProbe:
    failureThreshold: 10
    periodSeconds: 10
    timeoutSeconds: 5

  startupProbe:
    failureThreshold: 10
    periodSeconds: 10
    timeoutSeconds: 5
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-tpl
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    suspend: true
  compression: bzip2
  storage:
    s3:
      bucket: database
      prefix: mariadb-repl/recovery
      endpoint: minio.storage.svc.cluster.local:443
      accessKeyIdSecretKeyRef:
        name: minio
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: minio
        key: secret-access-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: homelab-bundle
          key: ca.crt
  timeout: 1h
  podAffinity: true
  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 1
      memory: 512Mi