apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-nfs
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "*/5 * * * *"
    suspend: false
    immediate: true
  compression: bzip2
  storage:
    volume:
      nfs:
        server: 10.0.0.50
        path: /volume1/mariadb
  timeout: 1h
  podAffinity: true
  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 1
      memory: 512Mi