apiVersion: batch/v1
kind: CronJob
metadata:
  name: sysbench
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          tolerations:
            - effect: NoSchedule
              key: node.mmontes.io/type
              value: compute-xlarge
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node.mmontes.io/type
                        operator: In
                        values:
                          - compute-xlarge
          containers:
          - name: sysbench-prepare
            image: severalnines/sysbench
            command:
              - sysbench
              - oltp_read_write
              - --tables=5
              - --table_size=1000000
              - --mysql-host=mariadb-primary.default.svc.cluster.local
              - --mysql-port=3306
              - --mysql-user=sbtest
              - --mysql-password=MariaDB11!
              - --mysql-db=sbtest
              - --time=300 
              - --threads=64
              - --report-interval=1
              - run
            resources:
              requests:
                cpu: "1"
                memory: 512Mi
              limits:
                memory: 512Mi