apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
spec:
  replicas: 2

  mariaDbRef:
    name: mariadb

  services:
    - name: rw-router
      router: readwritesplit
      listener:
        port: 3306

  auth:
    generate: true
    adminUsername: mariadb-operator
    adminPasswordSecretKeyRef:
      name: maxscale
      key: password
    
  metrics:
    enabled: true

  resources:
    requests:
      cpu: 2
      memory: 1Gi
    limits:
      cpu: 2
      memory: 1Gi

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - maxscale
        topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.mmontes.io/type
                operator: In
                values:
                  - compute-large