apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  storage:
    size: 30Gi
    storageClassName: topolvm

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        storageClassName: topolvm
        resources:
          requests:
            storage: 100Mi
        accessModes:
          - ReadWriteOnce

  metrics:
    enabled: true

  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      memory: 4Gi

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=3200MB
    max_allowed_packet=1GB

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  affinity:
    antiAffinityEnabled: true
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.mmontes.io/type
                operator: In
                values:
                  - compute-large
